### ISSUE TITLE
run r function method in separate thread

### ISSUE THREAD

**Issue by rcannood** [dynverse/dynwrap#109]
allows for:
* loading packages without messing up downstream environments
* interrupting computations even when c++ code is being executed?

**Comment by zouter** [comment]
Good idea, have a look at the runt package

**Comment by zouter** [comment]
To understand this right, this is for non-docker TI methods right?

I actually meant the callr package: https://github.com/r-lib/callr

**Comment by zouter** [comment]
I think having to run this in a separate R session kind of defeats the purpose of having an run R function. If you really need custom libraries, I think it is best if you just create an R package containing your R wrapper function, and doing `@import` or something on that function...

**Comment by zouter** [comment]
Closing this
