### ISSUE TITLE
Questions about add_dimred

### ISSUE THREAD

**Issue by QidiFeng** [dynverse/dynwrap#137]
Hi, the dynverse group,

This is a fantastic tool! I have a question on add_dimred():
I want to compare the performance of different dimension reduction methods (including my own method) on trajectory inference. I planed to offer different dimension reduced data (through different DR methods) during preparing the data by add_dimred(). Then I used infer_trajectory() with Slingshot wrapped in dynmethods, So will it use the dimension reduction information I provied? Or it still use the pca function inside Slingshot? Looking forward your response~ Thank you!

Best,
Qidi

**Comment by zouter** [comment]
Hi @QidiFeng 

This is something we might add in the future, but it's currently not possible, sorry :disappointed: . For now, you'll have to run slingshot yourself, which luckily isn't too hard for slingshot. Might I suggest our slingshot wrapper script: https://github.com/dynverse/ti_slingshot/blob/master/run.R , it also contains at the end the code to convert it to a dynwrap object.

Best
Wouter
