### ISSUE TITLE
Pseudotime calculation after rooting produces Inf scores

### ISSUE THREAD

**Issue by jma1991** [dynverse/dynwrap#139]
After calculating a trajectory and changing the root milestone I want to colour the trajectory by the pseudotime:

`plot_dimred(mod, "pseudotime", pseudotime = calculate_pseudotime(mod))`

However, the pseudotime scores for cells in a particular branch returned by the calculate_pseudotime function are infinite:
 
![PastedGraphic-3](https://user-images.githubusercontent.com/11476522/59039455-c84f5a80-886c-11e9-9886-b9ea050acc91.png)

I assumed that pseudotime would be calculated from the root milestone in either direction?

Package versions:
- dyno_0.1.1
- dynwrap_1.1.3
- dynplot_1.0.1
- dynmethods_1.0.1
- dynguidelines_1.0.0
- dynfeature_1.0.0

**Comment by rcannood** [comment]
This is indeed not supposed to happen! 

Could you give me a minimum reproducible example? I can't seem to replicate it with an example of my own.

Kind regards,
Robrecht

```r
library(dyno)
set.seed(1)
mod <- dyntoy::generate_dataset(
  model = dyntoy::model_multifurcating(num_branchpoints = 1, max_degree = 4)
) 
plot_dimred(
  mod,
  "pseudotime", 
  pseudotime = calculate_pseudotime(mod), 
  label_milestones = TRUE
)
```
![Screenshot from 2019-10-11 16-51-22](https://user-images.githubusercontent.com/553642/66661509-6a31ea00-ec47-11e9-8496-bd5cb0512593.png)

```r
mod2 <- mod %>% add_root(root_milestone_id = "M4")
plot_dimred(
  mod2,
  "pseudotime", 
  pseudotime = calculate_pseudotime(mod2), 
  label_milestones = TRUE
)
```
![Screenshot from 2019-10-11 16-51-30](https://user-images.githubusercontent.com/553642/66661518-6dc57100-ec47-11e9-84b7-7694a480418a.png)

**Comment by jma1991** [comment]
Sure, here is a link to an example dataset and script to reproduce the problem: https://www.dropbox.com/sh/1uh7ilwujfai2o5/AACJaPTR0cW8102fFSYGI94-a?dl=0

Thanks,
James

**Comment by rcannood** [comment]
Thanks for bringing this bug to light! The problem only occurred when calculating pseudotime of a trajectory where the root milestone has more than one transition. The devel branch should solve your problem. At the next release of dynwrap, the bug fix will be merged into the master branch :)

**Comment by jma1991** [comment]
Thanks for the quick fix, many thanks!

**Comment by rcannood** [comment]
Just to demonstrate:
```r
library(tidyverse)
library(dyno)
library(M3Drop)

sce <- readRDS("~/Downloads/dynverse/example.rds")
dat <- wrap_expression(
  expression = t(logcounts(sce)),
  counts = t(counts(sce)),
)

mod <- infer_trajectory(dat, "slingshot", seed = 1701)
before <- plot_dimred(mod, label_milestones = TRUE, pseudotime = calculate_pseudotime(mod))

mod2 <- add_root(mod, root_milestone_id = "1")
after <- plot_dimred(mod2, label_milestones = TRUE, pseudotime = calculate_pseudotime(mod))

patchwork::wrap_plots(before + labs(title = "Before rooting"), after + labs(title = "After rooting"))
ggsave("~/plot.png", width = 8, height = 4)
```
![plot](https://user-images.githubusercontent.com/553642/66699045-aa46aa80-ece3-11e9-9b34-e894dcbbf064.png)
