### ISSUE TITLE
Error to open website: http://guidelines.dynverse.org

### ISSUE THREAD

**Issue by Tina-Siqi** [dynverse/dynwrap#165]
Hi,
Dynverse is a useful tool to infer and evaluate trajectories for single-cell RNA sequencing data. But I can't open http://guidelines.dynverse.org. Here is the error I've met:
![1686639200026](https://github.com/dynverse/dynwrap/assets/117060139/510df553-7b2c-4bce-841e-77eb8a003772)
I guess this is not a problem that I can solve.
Thanks!

**Comment by rcannood** [comment]
Hey @Tina-Siqi 

Thanks for reporting this! Something seems to have gone wrong with our recent domain transfer. I'll look into this.

Robrecht

**Comment by rcannood** [comment]
This was fixed a while back
