### ISSUE TITLE
Allow params to be NULLable

### ISSUE THREAD

**Issue by rcannood** [dynverse/dynwrap#41]

**Comment by rcannood** [comment]
![l0iydskekojrzg69g](https://user-images.githubusercontent.com/553642/41704248-05dc0c5e-7536-11e8-847d-898d6e3998cd.gif)
You have a day off, today! Stop working and have some fun :)

**Comment by zouter** [comment]
Yesh yesh, On it!! 👋

**Comment by zouter** [comment]
With Paramhelpers removed, this will be something for later
