### ISSUE TITLE
Add support for sparse matrices

### ISSUE THREAD

**Issue by zouter** [dynverse/dynwrap#74]

**Comment by rcannood** [comment]
:sweat_smile: Work in progress! 

[`add_expression()`](https://github.com/dynverse/dynwrap/blob/singularity3/R/wrap_add_expression.R#L27) will convert expression and counts matrices to sparse format, but the rest of dynwrap still needs to support this...

**Comment by zouter** [comment]
Rest of dynwrap supports this AFAIK

**Comment by zouter** [comment]
+ rest of dynverse ;)

**Comment by zouter** [comment]
Fixed by #125
