### ISSUE TITLE
FIx duplicate cell_ids and milestone_ids

### ISSUE THREAD

**Issue by zouter** [dynverse/dynwrap#99]
Related to dynverse/dyno#28

Eg. prefix duplications with an M

**Comment by zouter** [comment]
Wishbone also affected by this

**Comment by zouter** [comment]
@rcannood I don't remember, is it now possible to remove this requirement?

https://github.com/dynverse/dynwrap/blob/3b55c604a888d2d8de7bb2a86cbda09a257623f2/R/wrap_add_trajectory.R#L45

Only the geodesic distances are affected by this, right?

**Comment by zouter** [comment]
I will remove this requirement then :innocent:

**Comment by rcannood** [comment]
Thanks @zouter !
